//
// Copyright (c) 2019 IBM Corporation and others.
// Licensed under Creative Commons Attribution-NoDerivatives
// 4.0 International (CC BY-ND 4.0)
//   https://creativecommons.org/licenses/by-nd/4.0/
//
// Contributors:
//     IBM Corporation
//
//FIX: This whole block of metadata
:projectid: cloud-openshift
:page-layout: guide-multipane
:page-duration: 45 minutes 
:page-releasedate: 2019-05-29
:page-description: Explore how to deploy microservices to Red Hat OpenShift's public cloud. //NOTE: Same description as below
:page-tags: ['Kubernetes', 'Docker', 'Cloud'] 
:page-permalink: /guides/{projectid}
:page-related-guides: ['kubernetes-intro', 'kubernetes-microprofile-config', 'kubernetes-microprofile-health', 'istio-intro'] 
:common-includes: https://raw.githubusercontent.com/OpenLiberty/guides-common/master 
:source-highlighter: prettify
:page-seo-title: Deploying microservices to Openshift 
:page-seo-description: A tutorial on how to deploy microservices to Amazon EKS using Amazon Elastic Container Registry (ECR) as a private container registry. 
:guide-author: Open Liberty
= Deploying microservices to OpenShift Online

[.hidden]
NOTE: This repository contains the guide documentation source. To view the guide in published form, view it on the https://openliberty.io/guides/{projectid}.html[Open Liberty website^].

Explore how to deploy microservices to Red Hat OpenShift's public cloud. //NOTE: Same description as above

:kube: Kubernetes
:hashtag: #
:win: WINDOWS
:mac: MAC
:linux: LINUX
:system-api: http://[hostname]:31000/system/properties
:inventory-api: http://[hostname]:32000/inventory/systems


// =================================================================================================
// Introduction
// =================================================================================================

== What you'll learn 

You will learn how to deploy two microservices in Open Liberty containers to a built-in {kube}
cluster using OpenShift Online, Red Hat's public cloud platform.

Kubernetes is an open source container orchestrator that automates many tasks involved in 
deploying, managing, and scaling containerized applications. If you would like to learn
more about Kubernetes, check out the https://openliberty.io/guides/kubernetes-intro.html[Deploying microservices to Kubernetes^]
guide.

There are different cloud-based solutions for running your workloads in a {kube} cluster. 
A cloud-based infrastructure enables you to focus on developing your microservices without 
worrying about details related to the servers you deploy them to. Using a cloud helps 
you to easily scale and serve your microservices in a high-availability setup.

Red Hat OpenShift is available in multiple platforms. OpenShift Dedicated is Red Hat's private cloud platform. OpenShift Online is
Red Hat's public cloud platform. OpenShift Container Platform is Red Hat's private cloud application deployment and hosting platform, 
built on top of your own infastructure. This guide will use OpenShift Online, where you will host your own {kube} cluster on Red Hat's 
pubilc cloud, and deploy your containerized applications to.

The two microservices you will deploy are called `system` and `inventory`. 
The `system` microservice returns the JVM system properties of the running container. 
It also returns the pod’s name in the HTTP header, making replicas easy to distinguish 
from each other. The `inventory` microservice adds the properties from the `system` microservice 
to the inventory. This demonstrates how communication can be established between pods 
inside a cluster.


// =================================================================================================
// Prerequisites
// =================================================================================================

== Prerequisites

Before you begin, the following tools need to be installed:

- *Docker:* You need a containerization software for building containers. Kubernetes 
supports various container types, but you will use Docker in this guide. For installation 
instructions, refer to the official https://docs.docker.com/install/[Docker^] documentation.

- *oc:* You need the OpenShift command-line tool `oc` to interact with your {kube} cluster.
For installation instructions, refer to the official 
https://docs.openshift.com/online/getting_started/beyond_the_basics.html#btb-installing-the-openshift-cli[OpenShift Online^] documentation.

To verify that the OpenShift CLI is installed correctly, run the following command:

[role=command]
```
oc version
```


// =================================================================================================
// Getting Started
// =================================================================================================

[role=command]
include::{common-includes}/gitclone.adoc[]

// no "try what you'll build" section in this guide since it would be too long due to all setup the user will have to do.


// =================================================================================================
// Creating a Kubernetes cluster on OpenShift
// =================================================================================================

== Creating a Kubernetes cluster on OpenShift

Before you can deploy your microservices, you must create a {kube} cluster on OpenShift.

// =================================================================================================
// Provisioning a cluster
// =================================================================================================

=== Provisioning a cluster

To create a {kube} cluster, you must sign up for a Red Hat account, and select the OpenShift Online starter tier, which
includes access to their public cloud platform. To sign up, refer to the 
https://www.openshift.com/trial/[official website^].

Once your cluster is provisioned, you are given access to their online web console. To login to OpenShift using the CLI, 
navigate to the online web console `> [username] > Copy Login Command > Display Token > Log in with this token`.

[source, role="no_copy"]
```
oc login --token=[your-token] --server=https://api.[cluster-id].online-starter.openshift.com:[port]
```

OpenShift will prompt you to create a project, which you can do by simply running the following command:

[role=command]
```
oc new-project [project-name]
```


// =================================================================================================
// Deploying microservices to OpenShift Online
// =================================================================================================

== Deploying microservices to OpenShift Online

In this section, you will learn how to deploy two microservices in Open Liberty containers to a {kube}
cluster on OpenShift. You will build and containerize the `system` and `inventory` microservices, 
push them to a container registry, and then deploy them to your {kube} cluster. 

// =================================================================================================
// Building and containerizing the microservices
// =================================================================================================

=== Building and containerizing the microservices

The first step of deploying to {kube} is to build your microservices and containerize them.

The starting Java project, which you can find in the `start` directory, is a multi-module Maven
project. It is made up of the `system` and `inventory` microservices. Each microservice resides in its own directory,
`start/system` and `start/inventory`. Both of these directories contain a Dockerfile, which is necessary
for building the Docker images. If you're unfamiliar with Dockerfiles, check out the
https://openliberty.io/guides/docker.html[Using Docker containers to develop microservices^] guide.

If you're familiar with Maven and Docker, you might be tempted to run a Maven build first and then
use the `.war` file to build a Docker image. The projects are setup such that this process is automated
as a part of a single Maven build. It is created by using the `dockerfile-maven` plug-in. The plug-in automatically
picks up the Dockerfile that is located in the same directory as its POM file and builds a Docker image from it.

****
[system]#*{win}*#

On the Docker Desktop General Setting page, ensure that the option `Expose daemon on 
tcp://localhost:2375 without TLS` is enabled. This configuration is required by the `dockerfile-maven` 
part of the build.

****

Navigate to the `start` directory and run the following command:

[role=command]
```
mvn package
```

The `package` goal automatically starts the `dockerfile-maven:build` goal. It runs during the
`package` phase. This goal builds a Docker image from the Dockerfile that is located in the same directory
as the POM file.

During the build, you see various Docker messages that describe what images are being downloaded and
built. When the build finishes, run the following command to list all local Docker images:

[role=command]
```
docker images
```

Verify that the `system:1.0-SNAPSHOT` and `inventory:1.0-SNAPSHOT` images are listed among them, for example:

[source, role="no_copy"]
----
REPOSITORY                    TAG
system                        1.0-SNAPSHOT
inventory                     1.0-SNAPSHOT
open-liberty                  latest
----

If you don't see the `system:1.0-SNAPSHOT` and `inventory:1.0-SNAPSHOT` images, then check the Maven
build log for any potential errors.

// =================================================================================================
// Pushing the images to OpenShift's internal registry
// =================================================================================================

=== Pushing the images to OpenShift's internal registry

OpenShift provides an integrated container registry called OpenShift Container Registry (OCR) that adds the ability to 
automatically provision new image repositories on demand. This provides users with a built-in location for their 
application builds to push the resulting images.

To have the cluster use the created images, the local Docker images needs to be tagged and pushed. 

Ensure that you are logged into OpenShift, now run the following commands to tag your applications, making sure to replace 
`[cluster-id]` and `[project-name]` with their respective values:

[role=command]
```
docker tag system:1.0-SNAPSHOT default-route-openshift-image-registry.apps.[cluster-id].online-starter.openshift.com/[project-name]/system:1.0-SNAPSHOT && \
docker tag inventory:1.0-SNAPSHOT default-route-openshift-image-registry.apps.[cluster-id].online-starter.openshift.com/[project-name]/inventory:1.0-SNAPSHOT
```

Run the following commands to push your applications to the OCR repositories making sure to replace `[cluster-id]` and `[project-name]` 
with their respective values:

[role=command]
```
docker push default-route-openshift-image-registry.apps.[cluster-id].online-starter.openshift.com/[project-name]/system:1.0-SNAPSHOT && \
docker push default-route-openshift-image-registry.apps.[cluster-id].online-starter.openshift.com/[project-name]/inventory:1.0-SNAPSHOT
```

//TODO: Display the kubernetes.yaml file on the right-hand pane, or make the user create it.
Now apply the configuration that is contained in the kubernetes.yaml file to the 
OpenShift cluster by running the following command:

[role=command]
```
oc apply -f kubernetes.yaml
```

The configuration deploys both the `inventory` and the `system` application as well as creates services to allow for the
communication between the two containers internally. If successful you should see the following output:

[source, role="no_copy"]
```
deployment.apps/system-deployment created
deployment.apps/inventory-deployment created
service/system-service created
service/inventory-service created
```

//TODO: Elaborate on OpenShift routes
To access the services and therefore the application, you need to use a route. A route in OpenShift exposes a service at 
a hostname such as `www.your-web-app.com` so users can access the application. 

Simply run the following commands to expose your services:

[role=command]
```
oc expose svc/inventory-service && \
oc expose svc/system-service
```

//TODO: Maybe replace the hostname with a general one that we can link in the guide? 
Your applications can now be accessed through the URL which can be found in the web console under `Networking > Routes > Location`. 
It will be automatically formatted like so `http://inventory-service-[project-name].apps.[cluster-id].online-starter.openshift.com/`