kind: Template
metadata:
  name: "system-build-template"
objects:
  kind: ImageStream
  metadata:
    name: "system"
    labels:
      application: "system"
  kind: BuildConfig
  apiVersion: build.openshift.io/v1
  metadata:
    name: "system"
    labels:
      build: "system"
  spec:
    source:
      binary: {}
      type: Binary
    strategy:
      type: Docker